repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files

-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.31.0
    hooks:
    -   id: yamllint
        args: [--format, parsable, --strict]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.12

-   repo: local
    hooks:
    -   id: validate-manifest
        name: validate manifest
        entry: ./scripts/validate-uvx.sh
        language: system
        files: cad_manifest\.yaml$
