[project]
name = "hornet-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
     "httpx",
     "jsonschema",
     "requests",
]

[project.optional-dependencies]
test = [
     "pytest",
     "pytest-mock",
]


