name: Validate Schema File

on:
  push:
    paths:
      - 'schema/cad_manifest.schema.json'
  pull_request:
    paths:
      - 'schema/cad_manifest.schema.json'

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract schema URL using jq
        id: get_schema
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq -r ."$schema" schema/cad_manifest.schema.json'        

      - name: Validate JSON Schema
        uses: sourcemeta/jsonschema@v9.3.5
        with:
          command: validate
          args: >
            --schema ${{ steps.get_schema.outputs.value }}
            --instance schema/cad_manifest.schema.json

  validate-examples:
    runs-on: ubuntu-latest
    needs: validate-schema
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Extract schema URL using jq
        id: get_schema
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq -r ."$id" schema/cad_manifest.schema.json'

      - name: Validate Examples against Schema
        uses: sourcemeta/jsonschema@v9.3.5
        with:
          command: validate
          args: >
            --schema ${{ steps.get_schema.outputs.value }}
            --instance examples/*.json
