name: Validate CAD Manifests
on:
  push:
    paths:
      - 'examples/**cad_manifest.json'
      - 'schema/cad_manifest.schema.json'
  pull_request:
    paths:
      - 'examples/**cad_manifest.json'
      - 'schema/cad_manifest.schema.json'

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: find
        run: |
          echo "matrix=$(find examples -type f -name '*cad_manifest.json' | jq -R -s -c 'split(\"\\n\")[:-1]')" >> $GITHUB_OUTPUT

  validate:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Validate manifest against schema
        uses: sourcemeta/jsonschema@v11.0.0
        with:
          command: validate
          args: >
            schema/cad_manifest.schema.json
            "${{ matrix.file }}"
